# =============== Main Configuration ===============
# Default configs for my personal usage
# If you want to use this, make sure it is
# the way you like.
# Last Update: 09.24.2026
# All configs are based on official site below:
# https://sw.kovidgoyal.net/kitty/conf/

include ./configs/font.conf
include ./configs/colors.conf
include ./configs/cursor.conf
include ./configs/behavior.conf
include ./configs/window.conf
include ./configs/keybinds.conf
