scrollback_lines 2000

scrollback_pager less +G -R

wheel_scroll_multiplier 5.0

click_interval 0.5

select_by_word_characters :@-./_~?&=%+#

mouse_hide_wait 0.0

repaint_delay    10

input_delay 3

enable_audio_bell no

open_url_with default

term xterm-kitty

allow_remote_control yes
