# Since I'm using niri, don't need to use initial window size configuration
# Feel free to change

enabled_layouts *
remember_window_size   no
initial_window_width   640
initial_window_height  400

window_border_width 0
window_margin_width 15
hide_window_decorations yes
hide_window_decorations titlebar-only
